[package]
name = "aoc2021"
version = "0.1.0"
edition = "2021"


[lib]
proc-macro = true

[dependencies]
itertools = "0.10"

# lib proc-macro dependencies
syn = { version = "1.0", features = ["full"] }
quote = "1.0"